/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Loading world...": "世界加载中...（点击开始游戏）",
    "/": "/",
    "Carrot": "胡萝卜",
    "Categories": "类别",
    "Create your first plantation": "创建你的第一个种植园",
    "Create your first garden": "创建你的第一个花园",
    "Create your first forest": "创建你的第一片森林",
    "Daisy": "雏菊",
    "Economy": "经济",
    "Flowers": "鲜花",
    "left)": "剩余)",
    "Items": "物品",
    "Hay": "干草",
    "Make your first upgrade": "你的第一次升级",
    "Missions (": "任务 (",
    "Notification": "通知",
    "Requires": "需要",
    "Place your first handcart": "放置你的第一个手推车",
    "Place your first well": "放置你的第一口井",
    "Unlock Order": "解锁排序",
    "Welcome Back!": "欢迎回来!",
    "Screenshot Mode": "截屏模式",
    "Game Wiki": "游戏 Wiki",
    "Click the large seed button at the bottom of the screen 100 times to gather seeds manually.": "点击屏幕下方的大种子按钮100次，手动采集种子。",
    "Place a Handcart. It increases the bonus radius of nearby buildings.": "放置一辆手推车。它增加了附近建筑的加成半径。",
    "Place a Well. Wells provide a production bonus to nearby crops.": "放置一口水井。水井可以为附近的农作物提供产量加成。",
    "Upgrades (": "升级 (",
    "Generated:": "已生成:",
    "Go Home": "回家",
    "Level": "等级",
    "Placed:": "已放置:",
    "(Lvl": "(等级",
    "Click Power": "点击威力",
    "Cost:": "成本:",
    "Adds a +200% bonus to each manual click.": "每次手动点击增加+200%的加成。",
    "Achievements Unlocked": "解锁成就",
    "Advanced Info": "高级信息",
    "Close": "关闭",
    "Danger Zone": "危险区",
    "Game Options": "游戏选项",
    "Game Sounds": "游戏声音",
    "Keyboard Navigation": "键盘导航",
    "Manage your game settings and view world statistics.": "管理你的游戏设置和查看世界统计。",
    "Manual Seeds Generated": "手动生成种子",
    "Missions Completed": "已完成任务",
    "Open Wiki": "打开Wiki",
    "Player Statistics": "玩家统计",
    "Randomize Name": "随机名称",
    "Reset": "重置",
    "Reset World": "重置世界",
    "This action is irreversible.": "这种行为是不可逆转的。",
    "Total Seeds Produced": "累计产出种子数",
    "Total Time in World": "世界总时间",
    "Upgrades Purchased": "已购买升级",
    "World Name": "世界名称",
    "Descending": "倒序",
    "Ascending": "升序",
    "Finish (": "完成 (",
    "Next upgrade:": "下一个升级:",
    "Oak Tree": "橡树",
    "Order:": "排序:",
    "Production": "生产",
    "Production:": "生产:",
    "Soil:": "土壤:",
    "Sort by:": "排序:",
    "Mission Complete!": "任务完成!",
    "Stone Road": "石路",
    "seeds": "种子",
    "Well": "水井",
    "Placing a sufficient number of items from the same category (e.g., Trees, Flowers) adjacent to each other will form a special group, like a Forest or Garden. Every item within that group receives a significant production bonus.": "将足够数量的同类物品（例如树、花）放置在一起，就会形成一个特殊的组，就像森林或花园一样。该组中的每件物品都会获得显著的生产加成。",
    "Placing a large number of items from the same category (e.g., 25 Trees) adjacent to each other forms a special group (a Forest). Every item in the group receives a massive production bonus. Experiment with creating Forests, Gardens, and Plantations to maximize your output.": "将来自同一类别的大量项目（例如，25棵树）彼此相邻地放置形成一个特殊的组（森林）。组中的每件物品都会获得大量的生产奖励。尝试创建森林、花园和种植园来最大化你的产出。",
    "Buildings like the Well provide a percentage-based production bonus to all crops within their radius. The bonuses from different buildings stack, so a clever layout can lead to exponential growth.": "像水井这样的建筑为其半径内的所有作物提供基于百分比的产量奖励。来自不同建筑的奖励叠加在一起，所以一个聪明的布局可以导致指数级增长。",
    "Achievement": "成就",
    "Arrow Keys": "方向键",
    "Action": "动作",
    "Seeds Valley Idle is a tranquil idle game about cultivating a vast, procedurally generated world. Your main goal is to generate the universal currency, Seeds (🌱), to purchase new items, unlock powerful upgrades, and expand your world infinitely.": "《种子谷放置》是一款关于培育一个巨大的程序生成世界的宁静游戏。你的主要目标是生成通用货币，种子（🌱），购买新物品，解锁强大的升级，并无限扩展你的世界。",
    "The bonus from a group stacks with other bonuses, like those from Buildings. Furthermore, group bonuses can be increased by purchasing upgrades from the Upgrades panel on the right of the screen.": "来自群组的奖励会与其他奖励叠加，比如来自建筑物的奖励。此外，玩家可以通过在屏幕右侧的升级面板中购买升级道具而获得更多群组奖励。",
    "The Upgrades panel on the right is your path to power. You can upgrade individual items (e.g., make all Daisies produce more), enhance group bonuses (make all Forests more potent), and boost global stats like total production and click power.": "右侧的升级界面，就是你的力量之路。你可以升级单个物品（例如，让所有雏菊生产更多），增强群组奖励（让所有森林更强大），并提高整体统计数据，如总产量和点击量。",
    "Use your Seeds to buy items like Flowers, Vegetables, and Trees from the shop on the left. Once placed, these items will generate Seeds for you automatically, even while you're away.": "用你的种子在左边的商店里购买鲜花、蔬菜和树木。一旦放置，这些物品将自动为你生成种子，即使你不在。",
    "Zoom in / out": "放大 / 缩小",
    "Keys": "按键",
    "Groups": "群组",
    "Group Types": "群组类型",
    "Group Synergies:": "群组协同:",
    "Group Name": "群组名称",
    "Group Synergies": "群组协同",
    "General": "常规",
    "Garden": "花园",
    "Garden Plot": "花园地块",
    "Forest": "森林",
    "Enter": "回车键",
    "Escape": "Esc键",
    "Edit Mode": "编辑模式",
    "Finish editing": "完成编辑",
    "Controls & Shortcuts": "控制 & 快捷键",
    "Controls": "控制",
    "Trees": "树",
    "Vegetables": "蔬菜",
    "Item Category": "物品类型",
    "Key Mechanics": "关键机制",
    "Items Required": "需要物品",
    "Achievement Unlocked!": "成就已解锁!",
    "Boosts all production by an additional 10%.": "使所有产量额外增加10%。",
    "Generating new territory...": "正在生成新的领地...",
    "Global Production": "全局生产",
    "Patch of Green": "绿化带",
    "Needs dirt": "需要泥土",
    "Not enough seeds": "没有足够的种子",
    "Occupied": "被占用",
    "+1 radius to Buildings within 1 tiles.": "在1个地块内增加1个建筑半径。",
    "Buildings": "建筑",
    "Decorations": "装饰品",
    "Handcart": "手推车",
    "(est. increase)": "（增加）",
    "+100% production boost.": "+100% 生产提升.",
    "Garden Bonus": "花园加成",
    "Boosts Garden bonus by a fixed +25%. Requires 1 Garden(s).": "提高花园奖励固定+25%。需要1个花园。",
    "Rose": "玫瑰",
    "Level Up!": "升级了!",
    "Verdant Expanse": "苍翠无垠",
    "You've reached Level": "你达到了等级",
    "Expanded Irrigation": "扩大灌溉",
    "Increases water bonus radius to 2 tiles.": "水的加成半径增加到2地块。",
    "Place 10 stone road tiles. You can find them in the 'Decorations' category on the left.": "放置10个石头道路瓷砖。你可以在左侧的“装饰品”类别中找到它们。",
    "Place 25 or more Trees next to each other to form a Forest.": "放置25棵或更多的树彼此相邻形成一片森林。",
    "Place 25 or more Vegetables next to each other to form a Plantation for a large bonus.": "放置25个或更多的蔬菜彼此相邻，形成一个种植园，以获得大量奖励。",
    "% Production": "% 生产",
    "Base Radius:": "基础半径:",
    "Production Bonus:": "生产加成:",
    "tiles": "地块",
    "tree": "树",
    "Item Unlocked!": "物品已解锁!",
    "Continue": "继续",
    "Plantation": "种植园",
    "+25% to bonus effectiveness.": "+25%的加成效果。",
    "Plantation Bonus": "种植园加成",
    "Boosts Plantation bonus by a fixed +25%. Requires 1 Plantation(s).": "增加固定的+25%种植园加成。需要1个种植园。",
    "Map View": "地图视图",
    "Manual Generation:": "手动生成:",
    "Pan the map": "平移地图",
    "decoration": "装饰品",
    "Wood Barrel": "木桶",
    "Wood Log": "木材原木",
    "Pan": "平底锅",
    "Pine Tree": "松树",
    "vegetable": "蔬菜",
    "Water Tower": "水塔",
    "flower": "鲜花",
    "Lettuce": "生菜",
    "Sample": "样本",
    "Tulip": "郁金香",
    "Building Bonus:": "建筑加成:",
    "Water Bonus:": "水加成:",
    "Name": "名称",
    "Mouse Wheel": "鼠标滚轮",
    "Potato": "土豆",
    "Right Click": "右键点击",
    "Spacebar + Drag": "空格键 + 拖拽",
    "Tomato": "西红柿",
    "Unlocks at": "解锁于",
    "Upgrade Everything:": "升级一切:",
    "Unlock Condition": "解锁条件",
    "Windmill": "风车磨坊",
    "Ancient Woods": "古老的森林",
    "Young Forest": "年轻森林",
    "Forest Bonus": "森林加成",
    "Apple Tree": "苹果树",
    "As your income grows, you'll unlock permanent upgrades for your items, groups, and even global stats. Reinvesting your Seeds into these upgrades is crucial for progressing.": "随着你收入的增长，你将解锁你的物品、团体甚至全球属性的永久升级。将种子重新投入到这些升级中对于游戏进程至关重要。",
    "Building Bonuses:": "建筑加成：",
    "Checksum:": "校验和：",
    "Core Gameplay Loop": "核心游戏循环",
    "Debug Info": "调试信息",
    "Infinite World:": "无限世界：",
    "Introduction": "介绍",
    "isRaining:": "正在下雨：",
    "Passive Income:": "被动收入:",
    "Seeds Valley Idle - Game Wiki": "种子谷闲置-游戏Wiki",
    "Start by clicking the large Seed button at the bottom of the screen to manually gather your first Seeds.": "首先点击屏幕底部的大种子按钮，手动收集你的第一个种子。",
    "Strategic Placement:": "战略位置:",
    "The key to massive production lies in how you arrange your items. This is where the core strategy of the game unfolds.": "大规模生产的关键在于你如何安排你的物品。这是游戏核心策略展开的地方。",
    "The world is endless. As you pan to the edge of the known map, new territory will be procedurally generated for you to explore and cultivate.": "世界是无止境的。当你移动到已知地图的边缘时，程序将生成新的领土供你探索和培育。",
    "Upgrade System:": "升级系统:",
    "Validation": "验证",
    "Welcome to Seeds Valley Idle": "欢迎来到种子谷闲置",
    "World Seed:": "世界种子:",
    "Your guide to the mechanics and world of Seeds Valley.": "你对种子谷的机制和世界的指导。",
    "Bonus": "加成",
    "Cherry Tree": "樱桃树",
    "Close UI / Clear selection": "关闭UI /清除选择",
    "Sunflower": "向日葵",
    "Toggle between Pan/Select modes": "平移/选择模式之间的切换",
    "Use these controls to navigate your world and manage your items efficiently.": "使用这些控件来导航您的世界并有效地管理您的物品。",
    "Walnut Tree": "核桃树",
    "Warehouse": "仓库",
    "Plum Tree": "李子树",
    "Achievements are special milestones that reward you for progressing in the game. Unlocking them can grant you instant Seed bonuses or permanent boosts to your production.": "成就是奖励你在游戏中取得进展的特殊里程碑。解锁它们可以让你获得即时种子奖励或永久提升你的产量。",
    "Beyond Infinity": "超越无限",
    "Budding Grove": "萌芽丛林",
    "Concept of Growth": "增长概念",
    "Continental Gardener": "大陆园丁",
    "Cosmic Filament": "宇宙之丝",
    "First Growth": "初次成长",
    "Galactic Core": "银河核心",
    "Heart of the Forest": "森林之心",
    "Hyperdimensional Harvest": "超维度收获",
    "Idle Mastery": "放置精通",
    "Multiverse of Green": "绿色多元宇宙",
    "Nebula of Seeds": "种子星云",
    "Omega Point": "欧米茄点",
    "Planet of Bloom": "繁花星球",
    "Seedling's Start": "苗期开始",
    "Supercluster Farmer": "超集群农民",
    "System of Life": "生命系统",
    "The Final Bloom": "最终之花",
    "The First Seed": "第一颗种子",
    "The Great Stillness": "伟大的寂静",
    "The Unfolding": "展开之卷",
    "Thriving Meadow": "茂盛的草地",
    "Transcendence": "超越",
    "Universal Architect": "环球建筑师",
    "Valley Carver": "山谷雕刻者",
    "Buildings provide powerful bonuses to nearby items or generate seeds themselves.": "建筑可以为附近的物品提供强大的奖励，或者自己生成种子。",
    "Crops are your primary source of passive Seed generation. Group them together for production bonuses.": "农作物是被动产生种子的主要来源。将他们组合在一起以获得生产奖励。",
    "Crops": "作物",
    "Castle": "城堡",
    "Coconut Tree": "椰子树",
    "Olive Tree": "橄榄树",
    "Onion": "洋葱",
    "Orange Tree": "橙子树",
    "Orchid": "兰花",
    "These items are purely aesthetic and do not generate seeds or provide bonuses.": "这些物品是纯粹的美学，不会产生种子或提供奖励。",
    "Tavern": "酒馆",
    "Starting Home": "初始住宅",
    "Roads & Decorations": "道路与装饰",
    "Red Bell Pepper": "红灯笼椒",
    "Backspace": "退格键",
    "Context": "上下文",
    "Delete selected items": "删除选中的物品",
    "Almond Tree": "杏树",
    "Barn": "谷仓",
    "Base Bonus": "基础加成",
    "Base Cost": "基础成本",
    "Base SPS": "基础SPS",
    "Beehive": "蜂巢",
    "Beetroot": "甜菜根",
    "Broccoli": "西兰花",
    "Calla Lily": "马蹄莲",
    "Category": "类别",
    "Cauliflower": "花椰菜",
    "Church": "教堂",
    "Hibiscus": "木槿",
    "Hydrangea": "绣球花",
    "Old Stone House": "老石屋",
    "Pansy": "三色堇",
    "Payback (min)": "回报（分钟）",
    "Peasant House": "农家小屋",
    "Peony": "牡丹",
    "Simple House": "简易住宅",
    "Begin your journey and cultivate a world of your own.": "开始你的旅程，培养一个属于你自己的世界。",
    "button to manually gather Seeds.": "按钮，手动采集种子。",
    "button to return to your starting house. It will update if you change the house position.": "按钮返回起始位置。如果你改变房子的位置，它会更新。",
    "Choose Your Avatar": "选择你的头像",
    "Click the": "点击",
    "Click the large": "点击放大",
    "Group items together and use buildings to create powerful production synergies.": "将物品组合在一起并使用建筑物来创造强大的生产协同效应。",
    "Home": "首页",
    "How to Play": "玩法说明",
    "Items like flowers and trees will generate Seeds for you automatically.": "像花和树这样的物品会自动为你生成种子。",
    "Name Your World": "为你的世界命名",
    "or by holding": "或者按住",
    "Pan around with": "左右平移",
    "Start Growing": "开始生长",
    "Use Seeds to buy items from the shop on the left.": "使用种子从左边的商店购买物品。",
    "WASD": "WASD",
    "Welcome to Seeds Valley Idle!": "欢迎来到种子谷放置！",
    "Cancel": "取消",
    "This will permanently delete your current world and all of its progress. A new world will be generated.": "这将永久地删除你当前的世界和它的所有进展。一个新的世界将会诞生。",
    "Are you sure you want to reset?": "你确定要重置吗？",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "%": "%",
    "N/A": "N/A",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/s": "/秒",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^\-([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Q$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Instant (.+) Seeds$/, '立即获得 $1 种子'],
    [/^Produce (.+) total Seeds$/, '总计生产 $1 种子'],
    [/^Place (.+) roads$/, '放置 $1 道路'],
    [/^(.+) production to Tree, Flower, Vegetable within (.+) tiles.$/, '在 $2 地块范围内增加 $1 的树、花、蔬菜产量。'],
    [/^(.+) production to Building within (.+) tiles.$/, '在 $2 地块范围内增加 $1 的建筑产量。'],
    [/^Increases water bonus radius to (.+) tiles.$/, '增加水的加成半径到 $1 地块。'],
    [/^Boosts Forest bonus by a fixed (.+). Requires (.+) Forest\(s\).$/, '增加森林加成固定提升 $1。需要 $2 森林。'],
    [/^Generate (.+) seeds from clicks$/, '通过点击生成 $1 种子'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Water Tower$/, '$1 水塔'],
    [/^([\d\.,]+) Orange Tree$/, '$1 橙子树'],
    [/^([\d\.,]+) Warehouse$/, '$1 仓库'],
    [/^([\d\.,]+) Apple Tree$/, '$1 苹果树'],
    [/^([\d\.,]+) Calla Lily$/, '$1 马蹄莲'],
    [/^([\d\.,]+) Cauliflower$/, '$1 花椰菜'],
    [/^([\d\.,]+) Simple House$/, '$1 简易住宅'],
    [/^([\d\.,]+) Rose$/, '$1 玫瑰'],
    [/^([\d\.,]+) Pine Tree$/, '$1 松树'],
    [/^([\d\.,]+) Plum Tree$/, '$1 李子树'],
    [/^([\d\.,]+) Oak Tree$/, '$1 橡树'],
    [/^([\d\.,]+) Olive Tree$/, '$1 橄榄树'],
    [/^([\d\.,]+) Beehive$/, '$1 蜂巢'],
    [/^([\d\.,]+) Church$/, '$1 教堂'],
    [/^([\d\.,]+) Stone Road$/, '$1 石路'],
    [/^([\d\.,]+) Old Stone House$/, '$1 老石屋'],
    [/^([\d\.,]+) Almond Tree$/, '$1 杏树'],
    [/^([\d\.,]+) Cherry Tree$/, '$1 樱桃树'],
    [/^([\d\.,]+) Hydrangea$/, '$1 绣球花'],
    [/^([\d\.,]+) Lettuce$/, '$1 生菜'],
    [/^([\d\.,]+) Peony$/, '$1 牡丹'],
    [/^([\d\.,]+) Red Bell Pepper$/, '$1 红灯笼椒'],
    [/^([\d\.,]+) Walnut Tree$/, '$1 核桃树'],
    [/^([\d\.,]+) Peasant House$/, '$1 农家小屋'],
    [/^([\d\.,]+) Wood Log$/, '$1 木头原木'],
    [/^([\d\.,]+) Wood Barrel$/, '$1 木桶'],
    [/^([\d\.,]+) Tulip$/, '$1 郁金香'],
    [/^([\d\.,]+) Potato$/, '$1 土豆'],
    [/^([\d\.,]+) Sunflower$/, '$1 向日葵'],
    [/^([\d\.,]+) Tomato$/, '$1 西红柿'],
    [/^([\d\.,]+) Hibiscus$/, '$1 木槿'],
    [/^([\d\.,]+) Hay$/, '$1 干草'],
    [/^([\d\.,]+) Daisy$/, '$1 雏菊'],
    [/^([\d\.,]+) Broccoli$/, '$1 西蓝花'],
    [/^([\d\.,]+) Beetroot$/, '$1 甜菜根'],
    [/^([\d\.,]+) Handcart$/, '$1 手推车'],
    [/^([\d\.,]+) Onion$/, '$1 洋葱'],
    [/^([\d\.,]+) Orchid$/, '$1 兰花'],
    [/^([\d\.,]+) Carrot$/, '$1 胡萝卜'],
    [/^([\d\.,]+) Pansy$/, '$1 三色堇'],
    [/^([\d\.,]+) Well$/, '$1 水井'],
    [/^([\d\.,]+) Windmill$/, '$1 风车磨坊'],
    [/^([\d\.,]+) Barn$/, '$1 谷仓'],
    [/^([\d\.,]+) minute ago$/, '$1 分钟前'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^([\d\.,]+) day ago$/, '$1 天前'],
    [/^([\d\.,]+) days ago$/, '$1 天前'],
    [/^about ([\d\.,]+) minutes ago$/, '大约 $1 分钟前'],
    [/^about ([\d\.,]+) minute ago$/, '大约 $1 分钟前'],
    [/^about ([\d\.,]+) hour ago$/, '大约 $1 小时前'],
    [/^about ([\d\.,]+) hours ago$/, '大约 $1 小时前'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^\+(.+) seeds$/, '\+$1 种子'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);